### ISSUE TITLE
Remember Forever Nighthawk Quiz

### ISSUE THREAD

**Issue by Trystan-Schmits** [Trystan-Schmits/CSA1#1]
A. Before: ![Before Image 2024-08-27 11 49 28 AM](https://github.com/user-attachments/assets/3e9ac9c1-fbae-4e61-a0b6-a63767b3bf32)
![group Image](https://github.com/user-attachments/assets/8cb27bc0-d703-4505-900d-458b3973aabf)
B. ![image](https://github.com/user-attachments/assets/57b50b1f-4d64-4ec4-9af0-de0c143197cb)

2: [this github page](https://github.com/Trystan-Schmits/CSA1)

## what does rm do?
rm removes a directory
I don't recommend actually doing it unless you are prepared

**Comment by iKAN2025** [comment]
https://github.com/XavierTho/xavier_2025/issues/1
Team Review Ticket
